# Generated by Django 2.0.8 on 2019-01-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='escuela',
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.Escuela'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='ninguno', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='primer_apeido',
            field=models.CharField(default='ninguno', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='segundo_apeido',
            field=models.CharField(default='ninguno', max_length=250),
            preserve_default=False,
        ),

    ]
