# Generated by Django 2.0.8 on 2019-01-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='user',
            name='segundo_apellido',
        ),
    ]
