# Generated by Django 2.0.8 on 2019-01-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='escuela',
        ),
        migrations.AddField(
            model_name='grupo',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.Escuela'),
        ),
    ]
