# Generated by Django 2.0.8 on 2019-01-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20190104_2151'),
    ]

    operations = [
        migrations.RenameField('User', 'primer_apeido', 'primer_apellido'),
        migrations.RenameField('User', 'segundo_apeido', 'segundo_apellido'),
    ]
