# Generated by Django 2.0.8 on 2019-01-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20190110_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='salon.Escuela')),
                ('nombre', models.CharField(max_length=250)),
                ('nivel', models.CharField(max_length=250)),
            ],
        ),
    ]
