# Generated by Django 2.0.8 on 2019-01-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
