# Generated by Django 2.0.8 on 2019-01-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20190111_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.Escuela'),
        ),
    ]
