# Generated by Django 2.0.8 on 2019-01-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(to='salon.Curso'),
        ),
    ]
