# Generated by Django 2.0.8 on 2019-01-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20190113_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='escuela',
        ),
        migrations.AddField(
            model_name='grupo',
            name='escuela',
            field=models.ManyToManyField(to='salon.Escuela'),
        ),
    ]
