# Generated by Django 2.0.8 on 2019-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_auto_20190111_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='escuela',
        ),
        migrations.AddField(
            model_name='grupo',
            name='escuela',
            field=models.ManyToManyField(to='salon.Escuela'),
        ),
    ]
