# Generated by Django 2.0.8 on 2019-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_auto_20190113_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='escuela',
        ),
        migrations.AddField(
            model_name='user',
            name='escuela',
            field=models.ManyToManyField(to='salon.Escuela'),
        ),
    ]
