# Generated by Django 2.0.8 on 2019-01-20 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('puntaje', models.FloatField()),
                ('categoria', models.CharField(choices=[('ejclase', 'Ejercicios clase'), ('tarea', 'Tarea'), ('practica', 'Práctica'), ('examen', 'Examen'), ('extra', 'Extra'), ('proyecto', 'Proyecto')], max_length=50)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Seccion')),
            ],
        ),
    ]
