# Generated by Django 2.0.8 on 2019-01-21 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('ejclase', 'Ejercicios clase'), ('tarea', 'Tarea'), ('extra', 'Extra'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('practica', 'Práctica')], max_length=50),
        ),
    ]
