# Generated by Django 2.0.8 on 2019-01-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_auto_20190120_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.Grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('practica', 'Práctica'), ('extra', 'Extra'), ('ejclase', 'Ejercicios clase'), ('examen', 'Examen'), ('proyecto', 'Proyecto')], max_length=50),
        ),
    ]
