# Generated by Django 2.0.8 on 2019-01-22 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_auto_20190120_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionesAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Estudiante')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Seccion')),
            ],
        ),
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('ejclase', 'Ejercicios clase'), ('practica', 'Práctica'), ('examen', 'Examen'), ('tarea', 'Tarea'), ('extra', 'Extra'), ('proyecto', 'Proyecto')], max_length=50),
        ),
    ]
