# Generated by Django 2.0.8 on 2019-01-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_auto_20190121_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('extra', 'Extra'), ('examen', 'Examen'), ('practica', 'Práctica'), ('ejclase', 'Ejercicios clase'), ('proyecto', 'Proyecto'), ('tarea', 'Tarea')], max_length=50),
        ),
    ]
