# Generated by Django 2.0.8 on 2019-01-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0017_auto_20190123_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('ejclase', 'Ejercicios clase'), ('extra', 'Extra'), ('proyecto', 'Proyecto'), ('examen', 'Examen'), ('practica', 'Práctica')], max_length=50),
        ),
    ]
