# Generated by Django 2.0.8 on 2019-01-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_auto_20190123_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('ejclase', 'Ejercicios clase'), ('tarea', 'Tarea'), ('examen', 'Examen'), ('extra', 'Extra'), ('practica', 'Práctica')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntos',
            field=models.FloatField(default=0),
        ),
    ]
