# Generated by Django 2.0.8 on 2019-02-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0020_auto_20190123_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('practica', 'Práctica'), ('ejclase', 'Ejercicios clase'), ('examen', 'Examen'), ('extra', 'Extra'), ('tarea', 'Tarea')], max_length=50),
        ),
    ]
